server.servlet.context-path=/api
server.port=7373


spring.application.name=time-zone

spring.jpa.open-in-view=false

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.always-use-message-format=true
spring.messages.fallback-to-system-locale=false
